# This file is generated on https://www.bytebase.com/sql-review-guide#bb.sql-review.dev
# You can use it with the SQL Review Action https://github.com/marketplace/actions/sql-review
template: bb.sql-review.dev
ruleList:
  - type: engine.mysql.use-innodb # Doc: https://www.bytebase.com/docs/sql-review/review-rules/supported-rules#engine.mysql.use-innodb
    level: ERROR
  - type: table.require-pk # Doc: https://www.bytebase.com/docs/sql-review/review-rules/supported-rules#table.require-pk
    level: ERROR
  - type: table.no-foreign-key # Doc: https://www.bytebase.com/docs/sql-review/review-rules/supported-rules#table.no-foreign-key
    level: WARNING
  - type: table.drop-naming-convention # Doc: https://www.bytebase.com/docs/sql-review/review-rules/supported-rules#table.drop-naming-convention
    level: ERROR
    payload:
      format: _del$
  - type: statement.select.no-select-all # Doc: https://www.bytebase.com/docs/sql-review/review-rules/supported-rules#statement.select.no-select-all
    level: WARNING
  - type: statement.where.require # Doc: https://www.bytebase.com/docs/sql-review/review-rules/supported-rules#statement.where.require
    level: WARNING
  - type: statement.where.no-leading-wildcard-like # Doc: https://www.bytebase.com/docs/sql-review/review-rules/supported-rules#statement.where.no-leading-wildcard-like
    level: WARNING
  - type: naming.table # Doc: https://www.bytebase.com/docs/sql-review/review-rules/supported-rules#naming.table
    level: WARNING
    payload:
      format: ^[a-z]+(_[a-z]+)*$
      maxLength: 64
  - type: naming.column # Doc: https://www.bytebase.com/docs/sql-review/review-rules/supported-rules#naming.column
    level: WARNING
    payload:
      format: ^[a-z]+(_[a-z]+)*$
      maxLength: 64
  - type: naming.index.uk # Doc: https://www.bytebase.com/docs/sql-review/review-rules/supported-rules#naming.index.uk
    level: WARNING
    payload:
      format: ^uk_{{table}}_{{column_list}}$
      maxLength: 64
  - type: naming.index.pk # Doc: https://www.bytebase.com/docs/sql-review/review-rules/supported-rules#naming.index.pk
    level: WARNING
    payload:
      format: ^pk_{{table}}_{{column_list}}$
  - type: naming.index.idx # Doc: https://www.bytebase.com/docs/sql-review/review-rules/supported-rules#naming.index.idx
    level: WARNING
    payload:
      format: ^idx_{{table}}_{{column_list}}$
      maxLength: 64
  - type: naming.index.fk # Doc: https://www.bytebase.com/docs/sql-review/review-rules/supported-rules#naming.index.fk
    level: WARNING
    payload:
      format: ^fk_{{referencing_table}}_{{referencing_column}}_{{referenced_table}}_{{referenced_column}}$
      maxLength: 64
  - type: column.required # Doc: https://www.bytebase.com/docs/sql-review/review-rules/supported-rules#column.required
    level: WARNING
    payload:
      columnList:
        - id
        - created_ts
        - updated_ts
        - creator_id
        - updater_id
  - type: column.no-null # Doc: https://www.bytebase.com/docs/sql-review/review-rules/supported-rules#column.no-null
    level: WARNING
  - type: schema.backward-compatibility # Doc: https://www.bytebase.com/docs/sql-review/review-rules/supported-rules#schema.backward-compatibility
    level: WARNING
  - type: database.drop-empty-database # Doc: https://www.bytebase.com/docs/sql-review/review-rules/supported-rules#database.drop-empty-database
    level: ERROR